//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRadiate.Interfaces.CentricityInterface.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=10.49.174.96\\SQLEXPRESS;Database=CentricityInterface;User Id=sa;Password=m" +
            "ona^*vale1317")]
        public string InterfaceConnString {
            get {
                return ((string)(this["InterfaceConnString"]));
            }
            set {
                this["InterfaceConnString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DATA SOURCE=medora; PERSIST SECURITY INFO=True;USER ID=nmscript;Password=concordn" +
            "ms;Enlist=false;Self Tuning=false; Pooling=true; Connection Timeout=60;")]
        public string CentricityConnString {
            get {
                return ((string)(this["CentricityConnString"]));
            }
            set {
                this["CentricityConnString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CentricityModuleLauncherVisible {
            get {
                return ((bool)(this["CentricityModuleLauncherVisible"]));
            }
            set {
                this["CentricityModuleLauncherVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int CentricityModuleLauncherOrder {
            get {
                return ((int)(this["CentricityModuleLauncherOrder"]));
            }
            set {
                this["CentricityModuleLauncherOrder"] = value;
            }
        }
    }
}
