//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRadiate.Radiopharmacy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int DrawDoseWhiteboardToolPositionIndex {
            get {
                return ((int)(this["DrawDoseWhiteboardToolPositionIndex"]));
            }
            set {
                this["DrawDoseWhiteboardToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawDoseWhiteboardToolVisible {
            get {
                return ((bool)(this["DrawDoseWhiteboardToolVisible"]));
            }
            set {
                this["DrawDoseWhiteboardToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int GasAdministrationToolPositionIndex {
            get {
                return ((int)(this["GasAdministrationToolPositionIndex"]));
            }
            set {
                this["GasAdministrationToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GasAdministrationToolVisible {
            get {
                return ((bool)(this["GasAdministrationToolVisible"]));
            }
            set {
                this["GasAdministrationToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int PYPAdministrationToolPositionIndex {
            get {
                return ((int)(this["PYPAdministrationToolPositionIndex"]));
            }
            set {
                this["PYPAdministrationToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PYPAdministrationToolVisible {
            get {
                return ((bool)(this["PYPAdministrationToolVisible"]));
            }
            set {
                this["PYPAdministrationToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RadiopharmacyLauncerVisible {
            get {
                return ((bool)(this["RadiopharmacyLauncerVisible"]));
            }
            set {
                this["RadiopharmacyLauncerVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int RadiopharmacyLauncherOrder {
            get {
                return ((int)(this["RadiopharmacyLauncherOrder"]));
            }
            set {
                this["RadiopharmacyLauncherOrder"] = value;
            }
        }
    }
}
