//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRadiate.Whiteboard.Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TransportTypeColumnVisibility {
            get {
                return ((bool)(this["TransportTypeColumnVisibility"]));
            }
            set {
                this["TransportTypeColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public global::System.Windows.Controls.DataGridLength TransportTypeColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["TransportTypeColumnWidth"]));
            }
            set {
                this["TransportTypeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TransportTypeColumnDisplayIndex {
            get {
                return ((int)(this["TransportTypeColumnDisplayIndex"]));
            }
            set {
                this["TransportTypeColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PregnancyStatusColumnVisibility {
            get {
                return ((bool)(this["PregnancyStatusColumnVisibility"]));
            }
            set {
                this["PregnancyStatusColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength PregnancyStatusColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["PregnancyStatusColumnWidth"]));
            }
            set {
                this["PregnancyStatusColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PregnancyStatusColumnDisplayIndex {
            get {
                return ((int)(this["PregnancyStatusColumnDisplayIndex"]));
            }
            set {
                this["PregnancyStatusColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SexColumnVisibility {
            get {
                return ((bool)(this["SexColumnVisibility"]));
            }
            set {
                this["SexColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public global::System.Windows.Controls.DataGridLength SexColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["SexColumnWidth"]));
            }
            set {
                this["SexColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SexColumnDisplayIndex {
            get {
                return ((int)(this["SexColumnDisplayIndex"]));
            }
            set {
                this["SexColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScheduledArrivalTimeColumnVisibility {
            get {
                return ((bool)(this["ScheduledArrivalTimeColumnVisibility"]));
            }
            set {
                this["ScheduledArrivalTimeColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public global::System.Windows.Controls.DataGridLength ScheduledArrivalTimeColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["ScheduledArrivalTimeColumnWidth"]));
            }
            set {
                this["ScheduledArrivalTimeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ScheduledArrivalTimeColumnDisplayIndex {
            get {
                return ((int)(this["ScheduledArrivalTimeColumnDisplayIndex"]));
            }
            set {
                this["ScheduledArrivalTimeColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TitleColumnVisibility {
            get {
                return ((bool)(this["TitleColumnVisibility"]));
            }
            set {
                this["TitleColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public global::System.Windows.Controls.DataGridLength TitleColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["TitleColumnWidth"]));
            }
            set {
                this["TitleColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int TitleColumnDisplayIndex {
            get {
                return ((int)(this["TitleColumnDisplayIndex"]));
            }
            set {
                this["TitleColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GivenNamesColumnVisibility {
            get {
                return ((bool)(this["GivenNamesColumnVisibility"]));
            }
            set {
                this["GivenNamesColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public global::System.Windows.Controls.DataGridLength GivenNamesColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["GivenNamesColumnWidth"]));
            }
            set {
                this["GivenNamesColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int GivenNamesColumnDisplayIndex {
            get {
                return ((int)(this["GivenNamesColumnDisplayIndex"]));
            }
            set {
                this["GivenNamesColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SurnameColumnVisibility {
            get {
                return ((bool)(this["SurnameColumnVisibility"]));
            }
            set {
                this["SurnameColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public global::System.Windows.Controls.DataGridLength SurnameColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["SurnameColumnWidth"]));
            }
            set {
                this["SurnameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int SurnameColumnDisplayIndex {
            get {
                return ((int)(this["SurnameColumnDisplayIndex"]));
            }
            set {
                this["SurnameColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MRNColumnVisibility {
            get {
                return ((bool)(this["MRNColumnVisibility"]));
            }
            set {
                this["MRNColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public global::System.Windows.Controls.DataGridLength MRNColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["MRNColumnWidth"]));
            }
            set {
                this["MRNColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int MRNColumnDisplayIndex {
            get {
                return ((int)(this["MRNColumnDisplayIndex"]));
            }
            set {
                this["MRNColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DOBColumnVisibility {
            get {
                return ((bool)(this["DOBColumnVisibility"]));
            }
            set {
                this["DOBColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public global::System.Windows.Controls.DataGridLength DOBColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["DOBColumnWidth"]));
            }
            set {
                this["DOBColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DOBColumnDisplayIndex {
            get {
                return ((int)(this["DOBColumnDisplayIndex"]));
            }
            set {
                this["DOBColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AgeColumnVisibility {
            get {
                return ((bool)(this["AgeColumnVisibility"]));
            }
            set {
                this["AgeColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength AgeColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["AgeColumnWidth"]));
            }
            set {
                this["AgeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int AgeColumnDisplayIndex {
            get {
                return ((int)(this["AgeColumnDisplayIndex"]));
            }
            set {
                this["AgeColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StatusColumnVisibility {
            get {
                return ((bool)(this["StatusColumnVisibility"]));
            }
            set {
                this["StatusColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public global::System.Windows.Controls.DataGridLength StatusColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["StatusColumnWidth"]));
            }
            set {
                this["StatusColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int StatusColumnDisplayIndex {
            get {
                return ((int)(this["StatusColumnDisplayIndex"]));
            }
            set {
                this["StatusColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NameColumnVisibility {
            get {
                return ((bool)(this["NameColumnVisibility"]));
            }
            set {
                this["NameColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength NameColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["NameColumnWidth"]));
            }
            set {
                this["NameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int NameColumnDisplayIndex {
            get {
                return ((int)(this["NameColumnDisplayIndex"]));
            }
            set {
                this["NameColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WardColumnVisibility {
            get {
                return ((bool)(this["WardColumnVisibility"]));
            }
            set {
                this["WardColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength WardColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["WardColumnWidth"]));
            }
            set {
                this["WardColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int WardColumnDisplayIndex {
            get {
                return ((int)(this["WardColumnDisplayIndex"]));
            }
            set {
                this["WardColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HospitalColumnVisibility {
            get {
                return ((bool)(this["HospitalColumnVisibility"]));
            }
            set {
                this["HospitalColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength HospitalColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["HospitalColumnWidth"]));
            }
            set {
                this["HospitalColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int HospitalColumnDisplayIndex {
            get {
                return ((int)(this["HospitalColumnDisplayIndex"]));
            }
            set {
                this["HospitalColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CommentsColumnVisibility {
            get {
                return ((bool)(this["CommentsColumnVisibility"]));
            }
            set {
                this["CommentsColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public global::System.Windows.Controls.DataGridLength CommentsColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["CommentsColumnWidth"]));
            }
            set {
                this["CommentsColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int CommentsColumnDisplayIndex {
            get {
                return ((int)(this["CommentsColumnDisplayIndex"]));
            }
            set {
                this["CommentsColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DurationColumnVisibility {
            get {
                return ((bool)(this["DurationColumnVisibility"]));
            }
            set {
                this["DurationColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength DurationColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["DurationColumnWidth"]));
            }
            set {
                this["DurationColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int DurationColumnDisplayIndex {
            get {
                return ((int)(this["DurationColumnDisplayIndex"]));
            }
            set {
                this["DurationColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InjectionsColumnVisibility {
            get {
                return ((bool)(this["InjectionsColumnVisibility"]));
            }
            set {
                this["InjectionsColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength InjectionsColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["InjectionsColumnWidth"]));
            }
            set {
                this["InjectionsColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int InjectionsColumnDisplayIndex {
            get {
                return ((int)(this["InjectionsColumnDisplayIndex"]));
            }
            set {
                this["InjectionsColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScansColumnVisibility {
            get {
                return ((bool)(this["ScansColumnVisibility"]));
            }
            set {
                this["ScansColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength ScansColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["ScansColumnWidth"]));
            }
            set {
                this["ScansColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int ScansColumnDisplayIndex {
            get {
                return ((int)(this["ScansColumnDisplayIndex"]));
            }
            set {
                this["ScansColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkflowColumnVisibility {
            get {
                return ((bool)(this["WorkflowColumnVisibility"]));
            }
            set {
                this["WorkflowColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength WorkflowColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["WorkflowColumnWidth"]));
            }
            set {
                this["WorkflowColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int WorkflowColumnDisplayIndex {
            get {
                return ((int)(this["WorkflowColumnDisplayIndex"]));
            }
            set {
                this["WorkflowColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RoomColumnVisibility {
            get {
                return ((bool)(this["RoomColumnVisibility"]));
            }
            set {
                this["RoomColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength RoomColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["RoomColumnWidth"]));
            }
            set {
                this["RoomColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int RoomColumnDisplayIndex {
            get {
                return ((int)(this["RoomColumnDisplayIndex"]));
            }
            set {
                this["RoomColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CurrentTaskColumnVisibility {
            get {
                return ((bool)(this["CurrentTaskColumnVisibility"]));
            }
            set {
                this["CurrentTaskColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength CurrentTaskColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["CurrentTaskColumnWidth"]));
            }
            set {
                this["CurrentTaskColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int CurrentTaskColumnDisplayIndex {
            get {
                return ((int)(this["CurrentTaskColumnDisplayIndex"]));
            }
            set {
                this["CurrentTaskColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NextTaskColumnVisibility {
            get {
                return ((bool)(this["NextTaskColumnVisibility"]));
            }
            set {
                this["NextTaskColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength NextTaskColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["NextTaskColumnWidth"]));
            }
            set {
                this["NextTaskColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int NextTaskColumnDisplayIndex {
            get {
                return ((int)(this["NextTaskColumnDisplayIndex"]));
            }
            set {
                this["NextTaskColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CameraColumnVisibility {
            get {
                return ((bool)(this["CameraColumnVisibility"]));
            }
            set {
                this["CameraColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength CameraColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["CameraColumnWidth"]));
            }
            set {
                this["CameraColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int CameraColumnDisplayIndex {
            get {
                return ((int)(this["CameraColumnDisplayIndex"]));
            }
            set {
                this["CameraColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExcludeCompleted {
            get {
                return ((bool)(this["ExcludeCompleted"]));
            }
            set {
                this["ExcludeCompleted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExcludeCancelled {
            get {
                return ((bool)(this["ExcludeCancelled"]));
            }
            set {
                this["ExcludeCancelled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public string ChosenWhiteboard {
            get {
                return ((string)(this["ChosenWhiteboard"]));
            }
            set {
                this["ChosenWhiteboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BioHazardColumnVisibility {
            get {
                return ((bool)(this["BioHazardColumnVisibility"]));
            }
            set {
                this["BioHazardColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public global::System.Windows.Controls.DataGridLength BioHazardColumnWidth {
            get {
                return ((global::System.Windows.Controls.DataGridLength)(this["BioHazardColumnWidth"]));
            }
            set {
                this["BioHazardColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int BioHazardColumnDisplayIndex {
            get {
                return ((int)(this["BioHazardColumnDisplayIndex"]));
            }
            set {
                this["BioHazardColumnDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PatientDetailsToolPositionIndex {
            get {
                return ((int)(this["PatientDetailsToolPositionIndex"]));
            }
            set {
                this["PatientDetailsToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PatientDetailsToolVisible {
            get {
                return ((bool)(this["PatientDetailsToolVisible"]));
            }
            set {
                this["PatientDetailsToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CommentsToolPositionIndex {
            get {
                return ((int)(this["CommentsToolPositionIndex"]));
            }
            set {
                this["CommentsToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CommentsToolVisible {
            get {
                return ((bool)(this["CommentsToolVisible"]));
            }
            set {
                this["CommentsToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ArrivePatientToolPositionIndex {
            get {
                return ((int)(this["ArrivePatientToolPositionIndex"]));
            }
            set {
                this["ArrivePatientToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ArrivePatientToolVisible {
            get {
                return ((bool)(this["ArrivePatientToolVisible"]));
            }
            set {
                this["ArrivePatientToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int InjectPatientToolPositionIndex {
            get {
                return ((int)(this["InjectPatientToolPositionIndex"]));
            }
            set {
                this["InjectPatientToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InjectPatientToolVisible {
            get {
                return ((bool)(this["InjectPatientToolVisible"]));
            }
            set {
                this["InjectPatientToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CompleteAppointmentToolPositionIndex {
            get {
                return ((int)(this["CompleteAppointmentToolPositionIndex"]));
            }
            set {
                this["CompleteAppointmentToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CompleteAppointmentToolVisible {
            get {
                return ((bool)(this["CompleteAppointmentToolVisible"]));
            }
            set {
                this["CompleteAppointmentToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SaveLayoutToolPositionIndex {
            get {
                return ((int)(this["SaveLayoutToolPositionIndex"]));
            }
            set {
                this["SaveLayoutToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveLayoutToolVisible {
            get {
                return ((bool)(this["SaveLayoutToolVisible"]));
            }
            set {
                this["SaveLayoutToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int RefreshWhiteboardToolPositionIndex {
            get {
                return ((int)(this["RefreshWhiteboardToolPositionIndex"]));
            }
            set {
                this["RefreshWhiteboardToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RefreshWhiteboardToolVisible {
            get {
                return ((bool)(this["RefreshWhiteboardToolVisible"]));
            }
            set {
                this["RefreshWhiteboardToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int StudyReportToolPotisionIndex {
            get {
                return ((int)(this["StudyReportToolPotisionIndex"]));
            }
            set {
                this["StudyReportToolPotisionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StudyReportToolVisible {
            get {
                return ((bool)(this["StudyReportToolVisible"]));
            }
            set {
                this["StudyReportToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int TransplantTasksToolPositionIndex {
            get {
                return ((int)(this["TransplantTasksToolPositionIndex"]));
            }
            set {
                this["TransplantTasksToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TransplantTasksToolVisible {
            get {
                return ((bool)(this["TransplantTasksToolVisible"]));
            }
            set {
                this["TransplantTasksToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int AddressLabelToolPositionIndex {
            get {
                return ((int)(this["AddressLabelToolPositionIndex"]));
            }
            set {
                this["AddressLabelToolPositionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddressLabelToolVisible {
            get {
                return ((bool)(this["AddressLabelToolVisible"]));
            }
            set {
                this["AddressLabelToolVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WhiteboardLauncherVisible {
            get {
                return ((bool)(this["WhiteboardLauncherVisible"]));
            }
            set {
                this["WhiteboardLauncherVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int WhiteboardLauncherOrder {
            get {
                return ((int)(this["WhiteboardLauncherOrder"]));
            }
            set {
                this["WhiteboardLauncherOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HighlightArrived {
            get {
                return ((bool)(this["HighlightArrived"]));
            }
            set {
                this["HighlightArrived"] = value;
            }
        }
    }
}
