using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Text;

using iRadiate.Common.IO;
using iRadiate.Common;
using iRadiate.DataModel.Common;
using iRadiate.DataModel.HealthCare;
using iRadiate.DataModel.NucMed;
using iRadiate.DataModel.Radiopharmacy;

namespace iRadiate.DataModel.Test
{
    public class DataFiller
    {
        public static StandardDataLibrarian lib = new StandardDataLibrarian();
        public static void FillUsers()
        {
            int i = 0;
            DataTable dt = iRadiate.Common.IO.TextFileReader.ReadCSVFile("Users.csv", true);
            Console.WriteLine("Datatable created - " + dt.Rows.Count + " rows & " + dt.Columns.Count + " columns");
            foreach(DataRow r in dt.Rows)
            {
                User u = new User();
                u.DateOfBirth = Convert.ToDateTime(r["DateOfBirth"].ToString());
                if(r["Gender"].ToString() == "Other")
                {
                    u.Gender = Gender.Other;
                }
                if (r["Gender"].ToString() == "Male")
                {
                    u.Gender = Gender.Male;
                }
                if (r["Gender"].ToString() == "Female")
                {
                    u.Gender = Gender.Female;
                }
                u.LoginName = r["LoginName"].ToString();
                u.Title = r["Title"].ToString();
                u.GivenNames = r["GivenNames"].ToString();
                u.Surname = r["Surname"].ToString();
                u.Password = r["Password"].ToString();
                u.PinNumber = r["PinNumber"].ToString();
                DumpDataStoreItem(u);
               
                lib.SaveItem(u);
                //This method is especially for those situations where there are no users
                //so the first user will be the system user and creator of things generated by the datafiller
                if (i == 0)
                    Platform.CurrentUser = u;
            }
            Console.WriteLine();

        }

        public static void FillElements(EFDataRetriever retriever)
        {
            DataTable dt = iRadiate.Common.IO.TextFileReader.ReadCSVFile("Elements.csv", true);
            Console.WriteLine("Datatable created - " + dt.Rows.Count + " rows & " + dt.Columns.Count + " columns");
            foreach (DataRow r in dt.Rows)
            {
                Element el = new Element();
                el.AtomicNumber = Convert.ToInt16(r["Number"].ToString());
                el.Symbol = r["Sym."].ToString();
                el.Name = r["Name"].ToString();
                retriever.SaveItem(el);
                DumpDataStoreItem(el);
            }
        }

        public static void FillIsotopes()
        {
            DataTable dt = iRadiate.Common.IO.TextFileReader.ReadCSVFile("Isotopes.csv", true);
            foreach (DataRow r in dt.Rows)
            {
                Isotope iso = new Isotope();
                iso.Element = lib.GetItems(typeof(Element), new List<RetrievalCriteria>()).Where(x => (x as Element).Symbol == r["AtomicSymbol"].ToString()).First() as Element;
                iso.Weight = Convert.ToInt32(r["Weight"].ToString());
                iso.Metastable = Convert.ToBoolean(r["Metastable"].ToString());
                iso.HalfLife = Convert.ToDouble(r["HalfLife"].ToString());

                lib.SaveItem(iso);
                DumpDataStoreItem(iso);
            }
        }

        public static void FillRadiopharmaceuticals()
        {
            DataTable dt = iRadiate.Common.IO.TextFileReader.ReadCSVFile("Radiopharmacueticals.csv", true);
            foreach (DataRow r in dt.Rows)
            {
                Console.WriteLine(r["AtomicSymbol"].ToString() + " " + r["AtomicWeight"].ToString());
                Chemical rp = new Chemical();
                List<RetrievalCriteria> rcList = new List<RetrievalCriteria>();
                RetrievalCriteria rc1 = new RetrievalCriteria("Abbreviation", CriteraType.ExactTextMatch, r["AtomicSymbol"].ToString() + "-" + r["AtomicWeight"].ToString());
                rcList.Add(rc1);
                Isotope iso = lib.GetItems(typeof(Isotope), rcList).First() as Isotope;
                rp.Isotope = iso;
                rp.LigandAbbreviation = r["Ligand"].ToString();
                lib.SaveItem(rp);
            }
        }

        public static void DumpDataStoreItem(DataStoreItem d)
        {
            Console.WriteLine("*** " + d.ConcreteType.Name + " Data Dump ***");
            
            foreach(PropertyInfo p in d.GetType().GetProperties())
            {
                if (p.PropertyType.IsPrimitive || p.PropertyType == typeof(string) || p.PropertyType == typeof(DateTime))
                {
                    if(p.GetValue(d, null) != null)
                    {
                        Console.WriteLine(p.Name + ":\t" + p.GetValue(d, null).ToString());
                    }
                    else
                    {
                        Console.WriteLine(p.Name + ":\t NULL");
                    }
                    
                }
                else if(p.PropertyType is IDataStoreItem)
                {
                    //DumpDataStoreItem(d);
                }
                

            }
            Console.WriteLine("*** End Data Dump ***");
        }

        public static void FillPatients(EFDataRetriever retriever)
        {
            DataTable dt = iRadiate.Common.IO.TextFileReader.ReadCSVFile("Patients.csv", true);
            Console.WriteLine("Datatable created - " + dt.Rows.Count + " rows & " + dt.Columns.Count + " columns");
            foreach (DataRow r in dt.Rows)
            {
                Patient p = new Patient();
                p.Surname = r["Surname"].ToString();
                p.GivenNames = r["GivenNames"].ToString();
                p.StreetNumber = new Random().Next(100).ToString();
                p.StreetName = r["StreetName"].ToString();
                p.TownName = r["Town"].ToString();
                p.MRN = r["MRN"].ToString();
                p.Title = r["Title"].ToString();
                p.HomePhone = r["HomePhone"].ToString();
                p.MobilePhone = r["MobilePhone"].ToString();
                if(r["Sex"].ToString() == "Male")
                {
                    p.Gender = Gender.Male;
                }
                else
                {
                    p.Gender = Gender.Female;
                }
                string[] dates = r["DateOfBirth"].ToString().Split('/');
                p.DateOfBirth = new DateTime(Convert.ToInt16(dates[2]), Convert.ToInt16(dates[1]), Convert.ToInt16(dates[0]));
                
                retriever.SaveItem(p);
                DumpDataStoreItem(p);
            }
        }
    }
}
